version: '3'
services:
  php:
    image: eu.gcr.io/struo-solutions/php:8.0-dev
    container_name: triasto_ssm_paramaters_bundle_php
    volumes:
      - '.:/var/www/html:rw'
      - '~/.composer:/home/php/.composer'
      - 'fpm_sock:/sock'
    environment:
      SYMFONY_REQUIRE: '5.*'
    networks:
      development: null

networks:
  development:
    external: true
    name: 'development'

volumes:
  fpm_sock:
    driver: local