version: '3'
services:
  php:
    image: prooph/composer:8.0
    volumes:
      - '.:/app:rw'
      - '~/.composer:/root/.composer'
    entrypoint: ''
    environment:
      SYMFONY_REQUIRE: '5.*'
    networks:
      development: null

networks:
  development:
    external: true
    name: 'development'